# Generated by Django 6.0 on 2025-12-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='temp_password', max_length=128),
            preserve_default=False,
        ),
    ]
